/** API TYPES **/
export const TEAMS_LOADING = 'TEAMS_LOADING';
export const STANDINGS_LOADING = 'STANDINGS_LOADING';
export const SCORERS_LOADING = 'SCORERS_LOADING';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
export const TEAMS_LOADED = 'TEAMS_LOADED';
export const STANDINGS_LOADED = 'STANDINGS_LOADED';
export const SCORERS_LOADED = 'SCORERS_LOADED';
export const SCHEDULE_LOADED = 'SCHEDULE_LOADED';


export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";